// Code generated by protoc-gen-go. DO NOT EDIT.
// source: text_resource.proto

package text_resource_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTextRequest struct {
	TextId               string                  `protobuf:"bytes,1,opt,name=text_id,json=textId,proto3" json:"text_id"`
	Locale               string                  `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale"`
	Params               []*GetTextRequest_Param `protobuf:"bytes,3,rep,name=params,proto3" json:"params"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetTextRequest) Reset()         { *m = GetTextRequest{} }
func (m *GetTextRequest) String() string { return proto.CompactTextString(m) }
func (*GetTextRequest) ProtoMessage()    {}
func (*GetTextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9448d6f46476500, []int{0}
}

func (m *GetTextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTextRequest.Unmarshal(m, b)
}
func (m *GetTextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTextRequest.Marshal(b, m, deterministic)
}
func (m *GetTextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTextRequest.Merge(m, src)
}
func (m *GetTextRequest) XXX_Size() int {
	return xxx_messageInfo_GetTextRequest.Size(m)
}
func (m *GetTextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTextRequest proto.InternalMessageInfo

func (m *GetTextRequest) GetTextId() string {
	if m != nil {
		return m.TextId
	}
	return ""
}

func (m *GetTextRequest) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *GetTextRequest) GetParams() []*GetTextRequest_Param {
	if m != nil {
		return m.Params
	}
	return nil
}

type GetTextRequest_Param struct {
	Param                string   `protobuf:"bytes,1,opt,name=param,proto3" json:"param"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTextRequest_Param) Reset()         { *m = GetTextRequest_Param{} }
func (m *GetTextRequest_Param) String() string { return proto.CompactTextString(m) }
func (*GetTextRequest_Param) ProtoMessage()    {}
func (*GetTextRequest_Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9448d6f46476500, []int{0, 0}
}

func (m *GetTextRequest_Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTextRequest_Param.Unmarshal(m, b)
}
func (m *GetTextRequest_Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTextRequest_Param.Marshal(b, m, deterministic)
}
func (m *GetTextRequest_Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTextRequest_Param.Merge(m, src)
}
func (m *GetTextRequest_Param) XXX_Size() int {
	return xxx_messageInfo_GetTextRequest_Param.Size(m)
}
func (m *GetTextRequest_Param) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTextRequest_Param.DiscardUnknown(m)
}

var xxx_messageInfo_GetTextRequest_Param proto.InternalMessageInfo

func (m *GetTextRequest_Param) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

type GetTextResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTextResponse) Reset()         { *m = GetTextResponse{} }
func (m *GetTextResponse) String() string { return proto.CompactTextString(m) }
func (*GetTextResponse) ProtoMessage()    {}
func (*GetTextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9448d6f46476500, []int{1}
}

func (m *GetTextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTextResponse.Unmarshal(m, b)
}
func (m *GetTextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTextResponse.Marshal(b, m, deterministic)
}
func (m *GetTextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTextResponse.Merge(m, src)
}
func (m *GetTextResponse) XXX_Size() int {
	return xxx_messageInfo_GetTextResponse.Size(m)
}
func (m *GetTextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTextResponse proto.InternalMessageInfo

func (m *GetTextResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTextRequest)(nil), "text_resource_proto.GetTextRequest")
	proto.RegisterType((*GetTextRequest_Param)(nil), "text_resource_proto.GetTextRequest.Param")
	proto.RegisterType((*GetTextResponse)(nil), "text_resource_proto.GetTextResponse")
}

func init() { proto.RegisterFile("text_resource.proto", fileDescriptor_e9448d6f46476500) }

var fileDescriptor_e9448d6f46476500 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x49, 0xad, 0x28,
	0x89, 0x2f, 0x4a, 0x2d, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x42, 0x15, 0x8c, 0x07, 0x0b, 0x2a, 0x2d, 0x66, 0xe4, 0xe2, 0x73, 0x4f, 0x2d, 0x09, 0x49, 0xad,
	0x28, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe7, 0x62, 0x07, 0xab, 0xcc, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0xc4, 0xb8, 0xd8,
	0x72, 0xf2, 0x93, 0x13, 0x73, 0x52, 0x25, 0x98, 0x20, 0xe2, 0x10, 0x9e, 0x90, 0x23, 0x17, 0x5b,
	0x41, 0x62, 0x51, 0x62, 0x6e, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xa6, 0x1e, 0x16,
	0x9b, 0xf4, 0x50, 0x6d, 0xd1, 0x0b, 0x00, 0xe9, 0x08, 0x82, 0x6a, 0x94, 0x92, 0xe5, 0x62, 0x05,
	0x0b, 0x08, 0x89, 0x70, 0xb1, 0x82, 0x85, 0xa0, 0x56, 0x43, 0x38, 0x4a, 0xaa, 0x5c, 0xfc, 0x70,
	0xed, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x20, 0x5b, 0xa0, 0xea, 0xc0,
	0x6c, 0xa3, 0x34, 0x2e, 0x1e, 0xa8, 0x1a, 0xb0, 0xc5, 0x42, 0x61, 0x5c, 0xec, 0x50, 0x6d, 0x42,
	0xca, 0x44, 0xb8, 0x49, 0x4a, 0x05, 0xbf, 0x22, 0x88, 0xcd, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x09,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x19, 0xfa, 0xc3, 0x67, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TextResourceClient is the client API for TextResource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TextResourceClient interface {
	GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error)
}

type textResourceClient struct {
	cc *grpc.ClientConn
}

func NewTextResourceClient(cc *grpc.ClientConn) TextResourceClient {
	return &textResourceClient{cc}
}

func (c *textResourceClient) GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error) {
	out := new(GetTextResponse)
	err := c.cc.Invoke(ctx, "/text_resource_proto.TextResource/GetText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextResourceServer is the server API for TextResource service.
type TextResourceServer interface {
	GetText(context.Context, *GetTextRequest) (*GetTextResponse, error)
}

// UnimplementedTextResourceServer can be embedded to have forward compatible implementations.
type UnimplementedTextResourceServer struct {
}

func (*UnimplementedTextResourceServer) GetText(ctx context.Context, req *GetTextRequest) (*GetTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetText not implemented")
}

func RegisterTextResourceServer(s *grpc.Server, srv TextResourceServer) {
	s.RegisterService(&_TextResource_serviceDesc, srv)
}

func _TextResource_GetText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextResourceServer).GetText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text_resource_proto.TextResource/GetText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextResourceServer).GetText(ctx, req.(*GetTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TextResource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "text_resource_proto.TextResource",
	HandlerType: (*TextResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetText",
			Handler:    _TextResource_GetText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "text_resource.proto",
}
